refinement_approximation_error: Work around JAX
JAX does not implement the transpose of the rather involved refinement
scan, thus work around this by using the JVP instead (utilizing that the
function is linear).